// Permission constants for the application

export const PermissionConstants = {
    // Merchant Operator
    READ_MERCHANT_OPERATOR: "READ_MERCHANT_OPERATOR",
    CREATE_MERCHANT_OPERATOR: "CREATE_MERCHANT_OPERATOR",
    DELETE_MERCHANT_OPERATOR : "DELETE_MERCHANT_OPERATOR",
    UPDATE_MERCHANT_OPERATOR: "UPDATE_MERCHANT_OPERATOR",
    RESET_MERCHANT_OPERATOR_PASSWORD: "RESET_MERCHANT_OPERATOR_PASSWORD",


    // Merchant Branch
    READ_MERCHANT_BRANCH: "READ_MERCHANT_BRANCH",
    CREATE_MERCHANT_BRANCH : "CREATE_MERCHANT_BRANCH",
    DELETE_MERCHANT_BRANCH : "DELETE_MERCHANT_BRANCH",
    UPDATE_MERCHANT_BRANCH: "UPDATE_MERCHANT_BRANCH",


    // Merchant Transactions
    READ_MERCHANT_BRANCH_TRANSACTION: "READ_MERCHANT_BRANCH_TRANSACTION",
    READ_MERCHANT_TRANSACTION: "READ_MERCHANT_TRANSACTION",
    INIT_MERCHANT_TRANSACTION: "INIT_MERCHANT_TRANSACTION",
};